name: MongoDB Server Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports:
          - 27017:27017
        
         

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install python-dotenv pymongo

    - name: Check MongoDB status
      run: docker ps -a

    - name: Run Python script with MongoDB
      env:
        SOME_SECRET: ${{ secrets.Mongo }}
      run: python demo.py > output.log

    - name: Upload log file
      uses: actions/upload-artifact@v4
      with:
        name: demo-log
        path: output.log